apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
  namespace: auto-repair
spec:
  backoffLimit: 4
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        app: db-migrate
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: ghcr.io/igorsantosxp/auto-repair-api:latest
          imagePullPolicy: IfNotPresent
          command: ["./bin/rails", "db:prepare"]
          envFrom:
            - configMapRef:
                name: api-config
            - secretRef:
                name: api-secrets
