apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - migrate-job.yaml
  - mailpit.yaml

commonLabels:
  app.kubernetes.io/part-of: auto-repair
